#!/usr/bin/ruby

# generatePages.rb
# Script to read all GIF images in the specified directory and create the
# ALFABURST monitor page.

require "erb"


print "Generating HTML pages..."
STDOUT.flush

indexPage = "index.htm"
indexPageERB = indexPage + ".erb"

timeNow = Time.now()
dateString = timeNow.strftime("%Y-%m-%d")
timeString = timeNow.strftime("%H:%M:%S")
@timestamp = "Autogenerated on #{dateString} at #{timeString} AST."

plots = Dir.glob("AllBeams_D*T*.gif")
@plots = plots

strERB = File.read(indexPageERB)
renderer = ERB.new(strERB)
result = renderer.result()

File.open(indexPage, "w") do |f|
  f.write(result)
end

puts "DONE\n"

