#!/usr/bin/ruby

# generatePages.rb
# Script to read all GIF images in the specified directory and create the
# ALFABURST monitor page.

require "erb"


print "Generating HTML pages..."
STDOUT.flush

indexPageERB = "/home/artemis/Survey/www/templates/index.htm.erb"
indexPage = "/home/artemis/Survey/www/index.htm"

epochPageERB = "/home/artemis/Survey/www/templates/epoch.htm.erb"
epochPagePrefix = "/home/artemis/Survey/www/epoch"

# generate index page
timeNow = Time.now()
dateString = timeNow.strftime("%Y-%m-%d")
timeString = timeNow.strftime("%H:%M:%S")
@timestamp = "Autogenerated on #{dateString} at #{timeString} AST."

plots = Dir.glob("/home/artemis/Survey/Data/Latest/AllBeams_D*T*.gif")
@plots = []
plots.size.times { |i| @plots << "images/" + File.basename(plots[i]) }

strERB = File.read(indexPageERB)
renderer = ERB.new(strERB)
result = renderer.result()

File.open(indexPage, "w") do |f|
  f.write(result)
end

# generate epoch pages
for plot in plots
  # extract epoch from plot file
  date = File.basename(plot).split("D")[1].split("T")[0]
  time = File.basename(plot).split("T")[1].split(".")[0]
  # define epoch
  @epoch = date + " " + time
  # build events file name
  @eventsFile = "events" + date + time + ".js"
  # build epoch page name
  epochPage = epochPagePrefix + date + time + ".htm"
  # render page
  strERB = File.read(epochPageERB)
  renderer = ERB.new(strERB)
  result = renderer.result()
  # write out file
  File.open(epochPage, "w") do |f|
    f.write(result)
  end
end

puts "DONE\n"

