#!/bin/bash

# for cron
source /home/artemis/.bashrc

rm -f /home/artemis/Survey/Flags/ALFABURST.FLAG
ssh artemis@abc0 "/home/artemis/Survey/Scripts/killobs"
ssh artemis@abc1 "/home/artemis/Survey/Scripts/killobs"
ssh artemis@abc2 "/home/artemis/Survey/Scripts/killobs"
ssh artemis@abc3 "/home/artemis/Survey/Scripts/killobs"
